import pdfMake from 'pdfmake/build/pdfmake';
import pdfFonts from 'pdfmake/build/vfs_fonts';

pdfMake.vfs = pdfFonts.pdfMake ? pdfFonts.pdfMake.vfs : pdfFonts.vfs;

const CYAN_COLOR = '#00D6D6';
const DARK_HEADER = '#2d3b47';
const LIGHT_GRAY = '#f8f9fa';

// Group colors for task categories
const GROUP_COLORS = {
  Removed: { header: '#ef4444', bg: '#fef2f2', text: '#b91c1c' },
  Added: { header: '#22c55e', bg: '#f0fdf4', text: '#15803d' },
  Later: { header: '#f59e0b', bg: '#fffbeb', text: '#b45309' },
  Earlier: { header: '#10b981', bg: '#ecfdf5', text: '#047857' },
  Modified: { header: '#3b82f6', bg: '#eff6ff', text: '#1d4ed8' },
  Other: { header: '#6b7280', bg: '#f9fafb', text: '#374151' }
};

// Group labels for bilingual support
const GROUP_LABELS = {
  Removed: { en: 'Removed Tasks', da: 'Fjernede opgaver' },
  Added: { en: 'Added Tasks', da: 'Tilføjede opgaver' },
  Later: { en: 'Delayed Tasks', da: 'Forsinkede opgaver' },
  Earlier: { en: 'Accelerated Tasks', da: 'Fremskyndede opgaver' },
  Modified: { en: 'Modified Tasks', da: 'Ændrede opgaver' },
  Other: { en: 'Other Tasks', da: 'Andre opgaver' }
};

// Extract difference type from row
const extractDifferenceType = (row, headers) => {
  const diffIndex = headers.findIndex(h => 
    h.toLowerCase().includes('difference') || 
    h.toLowerCase().includes('forskel')
  );
  
  if (diffIndex === -1 || !row.cells[diffIndex]) return 'Other';
  
  const text = row.cells[diffIndex].replace(/<[^>]*>/g, '').toLowerCase();
  
  if (text.includes('removed') || text.includes('fjernet')) return 'Removed';
  if (text.includes('added') || text.includes('tilføjet')) return 'Added';
  if (text.includes('later') || text.includes('senere') || text.includes('delay')) return 'Later';
  if (text.includes('earlier') || text.includes('tidligere') || text.includes('accelerat')) return 'Earlier';
  if (text.includes('modified') || text.includes('ændret') || text.includes('changed')) return 'Modified';
  
  return 'Other';
};

// Group rows by difference type
const groupRowsByType = (rows, headers) => {
  const groups = {};
  const order = ['Removed', 'Added', 'Later', 'Earlier', 'Modified', 'Other'];
  
  rows.forEach(row => {
    const type = extractDifferenceType(row, headers);
    if (!groups[type]) groups[type] = [];
    groups[type].push(row);
  });
  
  return order.filter(t => groups[t]?.length > 0).map(t => ({ type: t, rows: groups[t] }));
};

export const generateComparisonPDF = async ({
  sessionTitle,
  oldFileName,
  newFileName,
  userName,
  companyName,
  tableSections,
  summaryText,
  annotations,
  language = 'da'
}) => {
  console.log('📄 generateComparisonPDF called with:');
  console.log('📄 - sessionTitle:', sessionTitle);
  console.log('📄 - tableSections count:', tableSections?.length);
  console.log('📄 - annotations keys:', Object.keys(annotations || {}));
  const labels = {
    da: {
      reportTitle: 'Projekt Tidsplan Sammenligning',
      generatedOn: 'Genereret den',
      generatedBy: 'Genereret af',
      company: 'Virksomhed',
      oldVersion: 'Gammel Version',
      newVersion: 'Ny Version',
      summary: 'Sammenfatning af ændringer',
      resultsTable: 'Resultat Tabel',
      taskName: 'Opgave Navn',
      weekInA: 'Uge i A',
      weekInB: 'Uge i B',
      days: 'Dage',
      difference: 'Forskel',
      notes: 'Noter',
      comments: 'Kommentarer',
      page: 'Side',
      of: 'af',
      confidential: 'Fortroligt Dokument',
      poweredBy: 'Drevet af Nordic AI Group ApS',
      noData: 'Ingen data tilgængelig'
    },
    en: {
      reportTitle: 'Project Schedule Comparison',
      generatedOn: 'Generated on',
      generatedBy: 'Generated by',
      company: 'Company',
      oldVersion: 'Old Version',
      newVersion: 'New Version',
      summary: 'Summary of Changes',
      resultsTable: 'Results Table',
      taskName: 'Task Name',
      weekInA: 'Week in A',
      weekInB: 'Week in B',
      days: 'Days',
      difference: 'Difference',
      notes: 'Notes',
      comments: 'Comments',
      page: 'Page',
      of: 'of',
      confidential: 'Confidential Document',
      poweredBy: 'Powered by Nordic AI Group ApS',
      noData: 'No data available'
    }
  };

  const t = labels[language] || labels.da;
  const timestamp = new Date().toLocaleString(language === 'da' ? 'da-DK' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const coverPage = [
    { text: '', margin: [0, 80, 0, 0] },
    {
      canvas: [
        { type: 'rect', x: 0, y: 0, w: 515, h: 4, color: CYAN_COLOR }
      ],
      margin: [0, 0, 0, 30]
    },
    {
      text: 'NORDIC AI GROUP ApS',
      style: 'companyName',
      alignment: 'center',
      margin: [0, 0, 0, 10]
    },
    {
      text: 'AUTOMATE SMARTER',
      style: 'tagline',
      alignment: 'center',
      margin: [0, 8, 0, 40]
    },
    {
      canvas: [
        { type: 'rect', x: 100, y: 0, w: 315, h: 2, color: '#e0e0e0' }
      ],
      margin: [0, 0, 0, 40]
    },
    {
      text: t.reportTitle,
      style: 'coverTitle',
      alignment: 'center',
      margin: [0, 0, 0, 30]
    },
    {
      text: sessionTitle || 'Schedule Comparison Report',
      style: 'coverSubtitle',
      alignment: 'center',
      margin: [0, 0, 0, 50]
    },
    {
      table: {
        widths: ['*', '*'],
        body: [
          [
            { text: t.oldVersion, style: 'coverLabel', alignment: 'right', margin: [0, 5, 10, 5] },
            { text: oldFileName || 'N/A', style: 'coverValue', alignment: 'left', margin: [10, 5, 0, 5] }
          ],
          [
            { text: t.newVersion, style: 'coverLabel', alignment: 'right', margin: [0, 5, 10, 5] },
            { text: newFileName || 'N/A', style: 'coverValue', alignment: 'left', margin: [10, 5, 0, 5] }
          ]
        ]
      },
      layout: 'noBorders',
      margin: [50, 0, 50, 40]
    },
    {
      canvas: [
        { type: 'rect', x: 150, y: 0, w: 215, h: 1, color: '#e0e0e0' }
      ],
      margin: [0, 0, 0, 40]
    },
    {
      columns: [
        { width: '*', text: '' },
        {
          width: 'auto',
          table: {
            body: [
              [{ text: t.generatedOn + ':', style: 'metaLabel' }, { text: timestamp, style: 'metaValue' }],
              [{ text: t.generatedBy + ':', style: 'metaLabel' }, { text: userName || 'System', style: 'metaValue' }],
              [{ text: t.company + ':', style: 'metaLabel' }, { text: companyName || 'N/A', style: 'metaValue' }]
            ]
          },
          layout: 'noBorders'
        },
        { width: '*', text: '' }
      ],
      margin: [0, 0, 0, 60]
    },
    {
      text: t.confidential,
      style: 'confidential',
      alignment: 'center',
      margin: [0, 0, 0, 10]
    },
    {
      text: t.poweredBy,
      style: 'poweredBy',
      alignment: 'center'
    }
  ];

  const content = [
    ...coverPage,
    { text: '', pageBreak: 'after' }
  ];

  if (tableSections && tableSections.length > 0) {
    tableSections.forEach((section, sectionIdx) => {
      if (sectionIdx > 0) {
        content.push({ text: '', margin: [0, 20, 0, 0] });
      }

      // Results header with task count
      content.push({
        columns: [
          { text: `${t.resultsTable}`, style: 'sectionTitle', width: 'auto' },
          { text: `  (${section.rows.length} ${language === 'da' ? 'opgaver' : 'tasks'})`, style: 'taskCount', width: 'auto', margin: [5, 3, 0, 0] }
        ],
        margin: [0, 0, 0, 15]
      });

      // Group rows by difference type
      const groupedData = groupRowsByType(section.rows, section.headers);
      
      // Render each group with colored header
      groupedData.forEach((group, groupIdx) => {
        const colors = GROUP_COLORS[group.type] || GROUP_COLORS.Other;
        const label = GROUP_LABELS[group.type]?.[language] || GROUP_LABELS[group.type]?.en || group.type;
        
        // Group header with color accent
        content.push({
          table: {
            widths: ['*'],
            body: [[
              {
                columns: [
                  { 
                    canvas: [{ type: 'rect', x: 0, y: 2, w: 4, h: 14, color: colors.header }],
                    width: 8
                  },
                  { 
                    text: `${label} (${group.rows.length})`, 
                    style: 'groupHeader',
                    color: colors.text,
                    margin: [5, 0, 0, 0]
                  }
                ],
                fillColor: colors.bg,
                margin: [8, 6, 8, 6]
              }
            ]]
          },
          layout: {
            hLineWidth: () => 1,
            vLineWidth: () => 0,
            hLineColor: () => colors.header
          },
          margin: [0, groupIdx > 0 ? 15 : 0, 0, 5]
        });

        // Table headers
        const tableHeaders = section.headers.map(header => ({
          text: header,
          style: 'tableHeader',
          fillColor: DARK_HEADER
        }));

        const tableBody = [tableHeaders];

        // Table rows
        group.rows.forEach((row, rowIdx) => {
          const rowData = row.cells.map((cell, cellIdx) => {
            let cleanText = cell.replace(/<[^>]*>/g, '').trim();
            
            const isDifference = section.headers[cellIdx]?.toLowerCase().includes('difference') ||
                                section.headers[cellIdx]?.toLowerCase().includes('forskel');
            
            let textColor = '#333333';
            if (isDifference) {
              textColor = colors.text;
            }
            
            return {
              text: cleanText || '-',
              style: 'tableCell',
              color: textColor,
              fillColor: rowIdx % 2 === 0 ? '#ffffff' : LIGHT_GRAY
            };
          });
          tableBody.push(rowData);
        });

        // Push the table for this group
        content.push({
          table: {
            headerRows: 1,
            widths: section.headers.map(() => '*'),
            body: tableBody
          },
          layout: {
            hLineWidth: () => 0.5,
            vLineWidth: () => 0.5,
            hLineColor: () => '#e0e0e0',
            vLineColor: () => '#e0e0e0',
            paddingLeft: () => 6,
            paddingRight: () => 6,
            paddingTop: () => 4,
            paddingBottom: () => 4
          },
          margin: [0, 0, 0, 10]
        });
      }); // Close groupedData.forEach
      
    }); // Close tableSections.forEach
  }

  if (summaryText) {
    content.push({
      text: t.summary,
      style: 'sectionTitle',
      margin: [0, 20, 0, 10]
    });
    
    content.push({
      table: {
        widths: ['*'],
        body: [[{
          text: summaryText.replace(/<[^>]*>/g, '').trim(),
          style: 'summaryText',
          margin: [10, 10, 10, 10]
        }]]
      },
      layout: {
        hLineWidth: () => 1,
        vLineWidth: () => 1,
        hLineColor: () => CYAN_COLOR,
        vLineColor: () => CYAN_COLOR
      },
      margin: [0, 0, 0, 20]
    });
  }

  if (annotations && Object.keys(annotations).length > 0) {
    const hasComments = Object.values(annotations).some(arr => arr && arr.length > 0);
    
    if (hasComments) {
      content.push({
        text: t.comments,
        style: 'sectionTitle',
        margin: [0, 20, 0, 10]
      });

      Object.entries(annotations).forEach(([taskKey, taskAnnotations]) => {
        if (taskAnnotations && taskAnnotations.length > 0) {
          content.push({
            text: taskAnnotations[0]?.taskName || taskKey,
            style: 'commentTaskName',
            margin: [0, 5, 0, 5]
          });

          taskAnnotations.forEach(ann => {
            content.push({
              columns: [
                { width: 10, text: '•', color: CYAN_COLOR },
                {
                  width: '*',
                  stack: [
                    { text: ann.text, style: 'commentText' },
                    { 
                      text: `— ${ann.authorName || 'User'} (${new Date(ann.createdAt).toLocaleDateString(language === 'da' ? 'da-DK' : 'en-US')})`,
                      style: 'commentMeta'
                    }
                  ]
                }
              ],
              margin: [10, 2, 0, 5]
            });
          });
        }
      });
    }
  }

  const docDefinition = {
    pageSize: 'A4',
    pageMargins: [40, 60, 40, 60],
    content,
    styles: {
      companyName: {
        fontSize: 24,
        bold: true,
        color: DARK_HEADER
      },
      tagline: {
        fontSize: 12,
        color: CYAN_COLOR,
        letterSpacing: 2
      },
      coverTitle: {
        fontSize: 28,
        bold: true,
        color: DARK_HEADER
      },
      coverSubtitle: {
        fontSize: 16,
        color: '#666666'
      },
      coverLabel: {
        fontSize: 11,
        color: '#666666'
      },
      coverValue: {
        fontSize: 11,
        bold: true,
        color: DARK_HEADER
      },
      metaLabel: {
        fontSize: 10,
        color: '#666666',
        margin: [0, 2, 10, 2]
      },
      metaValue: {
        fontSize: 10,
        color: DARK_HEADER,
        margin: [0, 2, 0, 2]
      },
      confidential: {
        fontSize: 10,
        color: '#999999',
        italics: true
      },
      poweredBy: {
        fontSize: 9,
        color: CYAN_COLOR
      },
      sectionTitle: {
        fontSize: 14,
        bold: true,
        color: DARK_HEADER
      },
      groupHeader: {
        fontSize: 11,
        bold: true
      },
      tableHeader: {
        fontSize: 9,
        bold: true,
        color: '#ffffff'
      },
      tableCell: {
        fontSize: 8
      },
      taskCount: {
        fontSize: 9,
        color: '#666666',
        italics: true
      },
      summaryText: {
        fontSize: 10,
        color: '#333333',
        lineHeight: 1.4
      },
      commentTaskName: {
        fontSize: 10,
        bold: true,
        color: DARK_HEADER
      },
      commentText: {
        fontSize: 9,
        color: '#333333'
      },
      commentMeta: {
        fontSize: 8,
        color: '#999999',
        italics: true
      }
    },
    footer: (currentPage, pageCount) => {
      if (currentPage === 1) return null;
      return {
        columns: [
          { text: t.confidential, alignment: 'left', fontSize: 8, color: '#999999', margin: [40, 0, 0, 0] },
          { text: `${t.page} ${currentPage} ${t.of} ${pageCount}`, alignment: 'right', fontSize: 8, color: '#999999', margin: [0, 0, 40, 0] }
        ],
        margin: [0, 20, 0, 0]
      };
    },
    header: (currentPage) => {
      if (currentPage === 1) return null;
      return {
        columns: [
          { text: 'NORDIC AI GROUP ApS', alignment: 'left', fontSize: 8, color: CYAN_COLOR, bold: true, margin: [40, 20, 0, 0] },
          { text: sessionTitle || 'Report', alignment: 'right', fontSize: 8, color: '#999999', margin: [0, 20, 40, 0] }
        ]
      };
    }
  };

  return new Promise((resolve, reject) => {
    try {
      console.log('📄 Creating PDF document...');
      console.log('📄 docDefinition content items:', docDefinition.content?.length);
      console.log('📄 tableSections:', tableSections?.length);
      
      const pdfDoc = pdfMake.createPdf(docDefinition);
      console.log('📄 PDF document created successfully');
      
      const fileName = `${(sessionTitle || 'comparison-report').replace(/[^a-zA-Z0-9-_\s]/g, '')}_${new Date().toISOString().split('T')[0]}.pdf`;
      console.log('📄 Download filename:', fileName);
      
      // Use download method directly - more reliable
      pdfDoc.download(fileName);
      console.log('📄 PDF download triggered');
      resolve(true);
    } catch (error) {
      console.error('📄 PDF generation error:', error);
      reject(error);
    }
  });
};

export default generateComparisonPDF;
